### ISSUE TITLE
Cannot activate plugin - fresh install

### ISSUE THREAD

**Issue by falljer** [getherbert/herbert#172]
Recently, I had ran "composer update" on a project I have been working on for the past several months to install a new plugin, and I started getting a fatal error on the Wordpress site if the Herbert plugin is enabled.

So, to narrow down the cause of the problem, I tried a fresh Wordpress install in my dev environment (downloaded today from wordpress.org) with a fresh Herbert download into the plugins directory, no customizations.  Ran "composer install", and when I try to activate the plugin, I get the exact same message as my other project:

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider in /Users/jeremyfall/Projects/wordpress/wp-content/plugins/herbert-dev/vendor/illuminate/container/Container.php:819 Stack trace: #0 /Users/jeremyfall/Projects/wordpress/wp-content/plugins/herbert-dev/vendor/illuminate/container/Container.php(757): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter)) #1 /Users/jeremyfall/Projects/wordpress/wp-content/plugins/herbert-dev/vendor/illuminate/container/Container.php(732): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter)) #2 /Users/jeremyfall/Projects/wordpress/wp-content/plugins/herbert-dev/vendor/illuminate/container/Container.php(708): Illuminate\Container\Container->resolveDependencies(Array) #3 /Users/jeremyfall/Projects/wordpress/wp-content/plugins/herbert-dev/vendor/illuminate/container/Container.php(565): Illuminate\Contai in /Users/jeremyfall/Projects/wordpress/wp-content/plugins/herbert-dev/vendor/illuminate/container/Container.php on line 819

If I can fix it, I will provide an update to the project, since I use Herbert a lot, and now it looks like I can't use it on any new projects, or update existing ones.  But, I was hoping someone else had seen this, or could point me in the right direction here.

Thanks

**Comment by ken-bem** [comment]
On your composer.json file put "stable" in your minimum-stability field

**Comment by falljer** [comment]
Thanks @ken-bem that worked!  Question though: does this mean something is changing in Illuminate/Container that will break Herbert long-term?  I'm wondering if I should continue developing Wordpress plugins with Herbert if it's no longer being maintained.

**Comment by ken-bem** [comment]
Good that it did 💪🏽💪🏽. That is a good question, i feel there are 3 ways to tackle this problem:

1. Make a repository with the stable version and only update when herbet is updated

2. Make a repository and keep building in top of herbert, maybe even create a new herbert 👀( im thinkibg of doing this)

3. Create your own framework from scratch

**Comment by talss89** [comment]
Hi, sorry to hijack this issue, but I had the same problem as @falljer. Changing minimum-stability didn't help (and I did delete composer.lock and ./vendor).

Adding `"illuminate/container": "~5.1.0"` to my project's composer.json require section did fix the problem for me.

I think that might be preferable to changing minimum-stability.

Do you think it's worth a PR?

Tom.

**Comment by ken-bem** [comment]
Its definately worth a PR but you have to understand that it may take a while for someone to actually look at it, i suggest you create your own repository and make changes there, may help for new projects

**Comment by webstractions** [comment]
Thanks @talss89 for that fix.

**Comment by acermez** [comment]
Hi everyone,
The origin of this issue is that the Illuminate\container::make() in version 5.4 is only accepting one argument instead of two. This could be fixed by changing all the calls to the container make() to makeWith() which is a replacement of the original make() at illuminate\container < 5.4 .
Make sure to require 5.4.x-dev (at the time of this post, the makeWith() is not part of the latest 5.4 release).
It is not a good solution off course as it is not permanent but if I can create a repo with the fix, I will post back. If anyone can point me how to merge the changes to this repo, that would be great.
Thanks!

**Comment by wordpresspluginpro** [comment]
@acermez  LMFAO this issue literally sent me down a path to completely rewrite this concept from scratch.... 6 months later....here I am with a better version of it...  but, I'm really pleased with my discoveries and now I've got something awesome to work with...

Digging deeper into the Herbert I discovered some of the key problems with it:  Really you don't need the application class at all. (we're not using laravel in an application context)...  There's some ugly hacks (looks like the dev didn't understand how to use some WP plugin related functions) and in general I think it's a little bloated because of this.

I figured out how to create my own single file class that builds multiple containers, each for it's own plugin.  Then you can resolve the proper instance from there.  Maybe I'm not seeing why things are needed here but I've managed to rebuild this entire setup as a single file with a few extras to help with wp integration.  I would really love some feedback because I think it has a lot of potential.  I used Blade instead of twig, and I've got everything working so far.  Key thing was to use a "new Container" instead of trying to get an instance of the current one.

Feel free to poke around the repo on my profile (illumine-framework) I'll have the new release pushed out soon, I'm writing some documentation for it right now...

**The current version has an issue when using multiple plugins using the framework, But I resolved that problem this week and have been banging out new features and testing along the way which will be released soon.  The other issue is missing folders under the cache directory.  (.gitkeep missing)

Just add:
/cache/sessions/
/cache/views/
/cache/objects/

and it will load up just fine.

It's not compatible with Herbert because of this error, but if you activate the herbert based plugin first, my version will load.  (...herbert is using the application interface for some reason I'm yet to understand...)  Any Feedback would be great...

**Comment by webstractions** [comment]
@acermez  The differences between 5.3 to 5.4 are causing a lot of problems, not just in this package, but everywhere. And yes, the fork and create your own solution is the common way to deal with it.

**Comment by acermez** [comment]
@webstractions, Thank you for pointing that out! I did not test it much after making it work, so I will try to give it more time and more real life scenarios as I really like how Herbert is handling backend panels and routing. I have been trying other packages such as [Themosis Framework](http://framework.themosis.com/) to build plugins, and still can't find a great one with easy backend routing and Laravel like flexibility.

**Comment by webstractions** [comment]
@acermez Themeosis seems to be on top of it. It is not a package to build plugins with, however. It is targeted at bridging Laravel with WordPress, and seems to do good job. 

With that said, there probably is no right or wrong way of melding Laravel with WordPress. There are going to be some quirks.

I think projects like Herbert should not be advertised as a "plugin framework". It should be a Laravel Framework with WordPress as a dependancy. But that is just me.

**Comment by giangmd** [comment]
@talss89
Thanks. It's working for me now.

**Comment by 7x7x7eq51** [comment]
Hi All, i just fixed it! we need edit composer.json file

> `{
>     "name": "getherbert/herbert-plugin",
>     "description": "Herbert plugin",
>     "license": "MIT",
>     "require": {
>         "getherbert/framework": "~0.9",
>         "illuminate/contracts": "v5.1.1"
>     },
>     "config": {
>         "preferred-install": "dist"
>     },
>     "minimum-stability": "stable",
>     "autoload": {
>         "psr-4": {
>             "GHNShipping\\": "app/"
>         }
>     }
> }`


It's working for me.
