### ISSUE TITLE
Anyone got "Unresolvable dependency resolving"?

### ISSUE THREAD

**Issue by przor3n** [getherbert/herbert#184]
Got such error:
```
PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' 
with message 'Target [Illuminate\\Contracts\\Foundation\\Application] is not instantiable while building [Herbert\\Framework\\Providers\\HerbertServiceProvider].' 
in /home/red/Workspace/pandemonium/eventer/wp-content/plugins/eventer-plugin/vendor/illuminate/container/Container.php:895

Stack trace:
#0 /home/red/Workspace/pandemonium/eventer/wp-content/plugins/eventer-plugin/vendor/illuminate/container/Container.php(735): 
    Illuminate\\Container\\Container->notInstantiable('Illuminate\\\\Cont...')\n

#1 /home/red/Workspace/pandemonium/eventer/wp-content/plugins/eventer-plugin/vendor/illuminate/container/Container.php(608): Illuminate\\Container\\Container->build('Illuminate\\\\Cont...')
#2 /home/red/Workspace/pandemonium/eventer/wp-content/plugins/eventer-plugin/vendor/illuminate/container/Container.php(575): Illuminate\\Container\\Container->resolve('Illuminate\\\\Cont...')
#3 /home/red/Workspace/pandemonium/eventer/wp-content/plugins/eventer-plugin/vendo in /home/red/Workspace/pandemonium/eventer/wp-content/plugins/eventer-plugin/vendor/illuminate/container/Container.php on line 895
```

**Comment by cojocaru3** [comment]
+1

> Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider' in D:\xampp\htdocs\wp1\wp-content\plugins\krank\vendor\illuminate\container\Container.php:910 Stack trace: #0 D:\xampp\htdocs\wp1\wp-content\plugins\krank\vendor\illuminate\container\Container.php(848): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter)) #1 D:\xampp\htdocs\wp1\wp-content\plugins\krank\vendor\illuminate\container\Container.php(789): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter)) #2 D:\xampp\htdocs\wp1\wp-content\plugins\krank\vendor\illuminate\container\Container.php(758): Illuminate\Container\Container->resolveDependencies(Array) #3 D:\xampp\htdocs\wp1\wp-content\plugins\krank\vendor\illuminate\container\Container.php(608): Illuminate\Container\Container->build('Herbert\\Framewo...') #4 D:\xampp\htdocs\wp1\wp-content\plugins\kra in D:\xampp\htdocs\wp1\wp-content\plugins\krank\vendor\illuminate\container\Container.php on line 910

**Comment by phaberest** [comment]
It's already been discussed, but the workaround doesn't seem to work anymore. https://github.com/getherbert/herbert/issues/172#issuecomment-299024364

Forcing `"illuminate/container": "5.3"` and `"minimum-stability": "stable"` in `composer.json` seems to do the trick.

**Comment by jamesm010** [comment]
@przemekkot i just fixed mine editing `composer.json` adding `"illuminate/container": "v5.3.0", "illuminate/contracts": "v5.3.0"` and `"minimum-stability": "stable"`
