### ISSUE TITLE
open_basedir restriction in effect

### ISSUE THREAD

**Issue by roma-glushko** [getherbert/herbert#43]
I have got strange fatal error when I tried to deploy my plugin to production server:

```
Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/belislon/data:.) in /var/www/belislon/data/www/mango-magazine.com/wp-content/plugins/event-me/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 92

Fatal error: Uncaught exception 'Twig_Error_Loader' with message 'The "/" directory does not exist.' in /var/www/belislon/data/www/mango-magazine.com/wp-content/plugins/event-me/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:93 Stack trace: #0 /var/www/belislon/data/www/mango-magazine.com/wp-content/plugins/event-me/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(75): Twig_Loader_Filesystem->addPath('/', '__main__') #1 /var/www/belislon/data/www/mango-magazine.com/wp-content/plugins/event-me/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(33): Twig_Loader_Filesystem->setPaths('/') #2 /var/www/belislon/data/www/mango-magazine.com/wp-content/plugins/event-me/vendor/getherbert/framework/Herbert/Framework/Providers/TwigServiceProvider.php(23): Twig_Loader_Filesystem->__construct('/') #3 /var/www/belislon/data/www/mango-magazine.com/wp-content/plugins/event-me/vendor/illuminate/container/Container.php(719): Herbert\Framework\Providers\TwigServiceProvider->Herbert\Framework\Providers\{closure}(Object(Herbert\Framework\Applicat in /var/www/belislon/data/www/mango-magazine.com/wp-content/plugins/event-me/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 93
```

Whats wrong?

**Comment by brucevdkooij** [comment]
I ran into this as well. Obviously It's a permission issue of some sorts.

Not sure if you want to go this route but I worked around it myself by forking [the Herbert framework](https://github.com/getherbert/framework/) and [modifying `Herbert/Framework/Providers/TwigServiceProvider.php
`](https://github.com/brucevdkooij/getherbert-framework/commit/fef1eccbf88ab85db85b7abf52e0e6c3c4ac664c). Then I switched to my fork by adding this to my Herbert plugin's `composer.json`:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/brucevdkooij/getherbert-framework"
        }
    ]
```

And I also had to modify the require from `getherbert/framework` to `getherbert/herbert` since that is the [actual Composer package name](https://github.com/getherbert/framework/blob/dev/composer.json) because otherwise Composer wouldn't fetch the forked version.

P.S. Just FYI: for local development I actually make use of [piwi/composer-symlinker](https://github.com/piwi/composer-symlinker) which instead symbolically links the framework directory in vendor to a local directory where I can work on it. But that's entirely optional.

**Comment by JacobDorman** [comment]
I solved this by overriding the twig-loader binding

``` php
/*
 * Override twig loader to avoid open_basedir error
 */
$container->singleton('twig.loader', function ()
{
    $loader = new Twig_Loader_Filesystem('');

    foreach ($this->app->getPlugins() as $plugin)
    {
        $loader->addPath($plugin->getBasePath() . '/views', $plugin->getTwigNamespace());
    }

    return $loader;
});
```

also needed to do a similar thing with twig.options

``` php
// Fix deprecated autoescape value in twig.options
$twig_options = herbert( 'twig.options' );
$twig_options['autoescape'] = 'html';

$container->bind('twig.options', function () use ($twig_options) {
    return $twig_options;
});
```

**Comment by macker** [comment]
Yes indeed removing the / solved the problem. Thanks a lot
